version: "2"

services:
    enter:
        image: enter:latest
        network_mode: host
        volumes:
            - /home/ryukim/deploy/42_checkIn:/deploy/42_checkIn
        ports:
            - "3002:3000"
