version: "2"

services:
    enter:
        image: enter:latest
        volumes:
            - /home/ryukim/deploy/42_checkIn:/deploy/42_checkIn
        ports:
            - "3001:3000"
            - "3306:3306"
